# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/vivado/lab_13_led_right/led-blink.srcs/sources_1/bd/top_led_bd/ip/top_led_bd_processing_system7_0_0/top_led_bd_processing_system7_0_0.xci
# IP: The module: 'top_led_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/vivado/lab_13_led_right/led-blink.gen/sources_1/bd/top_led_bd/ip/top_led_bd_processing_system7_0_0/top_led_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_led_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/vivado/lab_13_led_right/led-blink.srcs/sources_1/bd/top_led_bd/ip/top_led_bd_processing_system7_0_0/top_led_bd_processing_system7_0_0.xci
# IP: The module: 'top_led_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/vivado/lab_13_led_right/led-blink.gen/sources_1/bd/top_led_bd/ip/top_led_bd_processing_system7_0_0/top_led_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_led_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
