# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aq/git/courses/digital-design-toolbox/lab4/lab45/check_251228_193806/testing_project.srcs/sources_1/bd/multiplier_16_bit_lut/ip/multiplier_16_bit_lut_mult_gen_0_0/multiplier_16_bit_lut_mult_gen_0_0.xci
# IP: The module: 'multiplier_16_bit_lut_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aq/git/courses/digital-design-toolbox/lab4/lab45/check_251228_193806/testing_project.gen/sources_1/bd/multiplier_16_bit_lut/ip/multiplier_16_bit_lut_mult_gen_0_0/multiplier_16_bit_lut_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier_16_bit_lut_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/aq/git/courses/digital-design-toolbox/lab4/lab45/check_251228_193806/testing_project.srcs/sources_1/bd/multiplier_16_bit_lut/ip/multiplier_16_bit_lut_mult_gen_0_0/multiplier_16_bit_lut_mult_gen_0_0.xci
# IP: The module: 'multiplier_16_bit_lut_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aq/git/courses/digital-design-toolbox/lab4/lab45/check_251228_193806/testing_project.gen/sources_1/bd/multiplier_16_bit_lut/ip/multiplier_16_bit_lut_mult_gen_0_0/multiplier_16_bit_lut_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier_16_bit_lut_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
