# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/cfg/Arty-7-master.xdc

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/cfg/partition_floorplan.xdc

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/cfg/Nexys-4-DDR-Master.xdc

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/cfg/ports.xdc

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/cfg/clocks.xdc

# Block Designs: bd/top_led_bd/top_led_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_led_bd || ORIG_REF_NAME==top_led_bd} -quiet] -quiet

# IP: bd/top_led_bd/ip/top_led_bd_processing_system7_0_0/top_led_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_led_bd_processing_system7_0_0 || ORIG_REF_NAME==top_led_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_led_bd/ip/top_led_bd_blink_counter_0_0/top_led_bd_blink_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_led_bd_blink_counter_0_0 || ORIG_REF_NAME==top_led_bd_blink_counter_0_0} -quiet] -quiet

# IP: bd/top_led_bd/ip/top_led_bd_shift_led_right_0_0/top_led_bd_shift_led_right_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_led_bd_shift_led_right_0_0 || ORIG_REF_NAME==top_led_bd_shift_led_right_0_0} -quiet] -quiet

# XDC: /home/aq/git/courses/digital-design-toolbox/lab13/lab_13_1/vivado/lab_13_led_right/led-blink.gen/sources_1/bd/top_led_bd/top_led_bd_ooc.xdc
