# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/multiplier_16_bit_lut/multiplier_16_bit_lut.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier_16_bit_lut || ORIG_REF_NAME==multiplier_16_bit_lut} -quiet] -quiet

# IP: bd/multiplier_16_bit_lut/ip/multiplier_16_bit_lut_mult_gen_0_0/multiplier_16_bit_lut_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier_16_bit_lut_mult_gen_0_0 || ORIG_REF_NAME==multiplier_16_bit_lut_mult_gen_0_0} -quiet] -quiet

# XDC: /home/aq/git/courses/digital-design-toolbox/lab4/lab45/check_251228_193806/testing_project.gen/sources_1/bd/multiplier_16_bit_lut/multiplier_16_bit_lut_ooc.xdc
